### PR TITLE
Make barrierQueue serial

### LINKED ISSUE #26: When.BarrierQueue
Hello! I found what barrier queue is concurrent:

Functions.swift:
```
let barrierQueue = DispatchQueue(label: "When.BarrierQueue", attributes: DispatchQueue.Attributes.concurrent)
```

But it must be `serial` to behave as real `barrier`. Misprint?

### PR DESCRIPTION
**Pull request by MontakOleg**
Resolves #26

### CODE REVIEW

**Comment by vadymmarkov** [comment]
Awesome, thanks @MontakOleg 👍

**Comment by MontakOleg** [comment]
Hm..
```
*** Skipped downloading Quick.framework binary due to the error:

	"Maximum number of login attempts exceeded. Please try again later."

*** Checking out Quick at "v1.1.0"
```

It looks like binary not available, so Carthage builds dependencies from sources using following command:
```
"travis_wait 35 carthage bootstrap --platform iOS,Mac"
```

Then tests run on tvOS platform
```
"xcodebuild test -project When.xcodeproj -scheme \"When-tvOS\" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' | xcpretty && exit ${PIPESTATUS[0]}"
```

And finally Quick not found for tvOS:
```
No such module 'Quick'
```

So we need add tvOS platform to Carthage bootstrap command like this:
```
"travis_wait 35 carthage bootstrap --platform iOS,Mac,tvOS"
```

**Comment by vadymmarkov** [comment]
Let's see how it goes.

**Comment by vadymmarkov** [comment]
@MontakOleg v3.0.1 is released 😉

**Pull request merged**
