### PR TITLE
Allowing multiple .then/.done/.fail/.always for the same promise

### PR DESCRIPTION
**Pull request by mallexxx**
It maybe confusing that a Promise may have only one .then (.done/.always/.fail)
I've added a possibility to add multiple handlers

### CODE REVIEW

**Comment by vadymmarkov** [comment]
Hi @mallexxx, sorry for late reply. Looks great 👍 Would you mind adding some tests?

**Comment by vadymmarkov** [comment]
I'm gonna merge this now, all the current tests passed, and we can add tests for multiple handlers later.

**Comment by mallexxx** [comment]
Sorry for the long answer, I'm afraid I've introduced a major problem there, race conditions leading to exc_bad_access appear when used heavily with threading. For now I switched to NSOperationQueue extended with promise-like syntax and inspired by apple's advanced NSOperations WWDC session. If I have time I'll debug it later, adding some NSLock-s may fix it.

**Comment by vadymmarkov** [comment]
@mallexxx was it introduced by adding multiple "then" handlers? I think at least multiple "success", "fail" and "always" shouldn't cause that problem.

**Comment by mallexxx** [comment]
I'm not sure, had no time to finish, but it seems like setting the result on one thread and then reading on another, or something to do with deallocating

**Comment by vadymmarkov** [comment]
Ok, no problem 😉 I did a revert to the previous tag because I'm planning to add a new feature and want to have a stable version on master. Feel free to re-open this PR when you figure out underlying problem.

**Comment by vadymmarkov** [comment]
It happened that I need this feature, so I added back the code to set multiple `fail`, `done` and `always`: https://github.com/vadymmarkov/When/pull/20. I think it was `then` that caused `exc_bad_access`, we can investigate it more and add it back when it's fixed. Now I have an opportunity to test another 3 handlers.

**Pull request merged**
