### PR TITLE
Swift PM support updated.

### PR DESCRIPTION
**Pull request by lomatrix**
Updated to Swift 5.

### CODE REVIEW

**Comment by lomatrix** [comment]
Maybe tag should be updated to 4.0.1

**Comment by vadymmarkov** [comment]
Thanks! Any idea why travis is failing?

**Comment by lomatrix** [comment]
I guess because of Swift 5. Xcode 10 is a minimum version for it. 
Possible solution: set _"osx_image": "xcode10.2"_ on CI or configure Swift PM to use toolchain version 4.2.

**Comment by lomatrix** [comment]
Are you going to update project to Swift 5 ? 
 You may create brach _when5_ where for MR with Swift PM manifest which uses  toolchain of version 5. And master will be on Swift 4.2.

**Review by vadymmarkov — APPROVED** [review]
Awesome 👍

**Comment by vadymmarkov** [comment]
I think it's about time to update the project to Swift 5 😉

**Pull request merged**
